const mongoose = require('mongoose');

const businessSchema=new mongoose.Schema({
    ownerName:{
        type:String,
        default:"saurav sable"
    },
    ownerId:{
        type:String,
        default:"6558bba9db814920bab1592c"
    },
    ownerEmail:{
        type:String,
        default:"Admin@gmail.com"
    },
    ownerImage:{
        type:String,
        default:"https://res.cloudinary.com/dlnkiwqfa/image/upload/v1700890727/gdigsqfldk4vliwgzfhm.svg"
    },
    link:{
        type:String
    },
    category:{
        type:String
    },
    businessName:{
        type:String
    },
    startDate:{
        type:Date
    },
    location:{
        type:String
    },
    projectName:{
        type:String
    },
    otherCategories:{
        type:Array
    },
    tagLine:{
        type:String
    },
    logoImage:{
        type:String
    },
    listingImage:{
        type:String
    },
    description:{
        type:String
    },
    monthlyProfit:{
        type:Number
    },
    monthlyRevenue:{
        type:Number
    },
    documentProof:{
        type:String
    },
    InstagramHandle:{
        type:String
    },
    InstagramHandleFollowers:{
        type:Number
    },
    TwitterHandle:{
        type:String
    },
    TwitterHandleFollowers:{
        type:Number
    },
    FacebookHandle:{
        type:String
    },
    FacebookHandleFollowers:{
        type:Number
    },
    YoutubeHandle:{
        type:String
    },
    YoutubeHandleFollowers:{
        type:Number
    },
    maxPrice:{
        type:Number
    },
    minPrice:{
        type:Number
    },
    offerReceived:{
        type:String,
        default:"no"
    }
});

module.exports = new mongoose.model('businessDatas',businessSchema);